// libs/veaury/dev-project-vue3/src/pages/basic/index.vue
<template>
  <h3>
    This example shows the basic usage of `applyReactInVue`.
  </h3>
  <h4>
    Using React components in Vue components.
  </h4>
  <Basic :foo="foo" ref="BasicRef" :null="null">
    <div class="slot">
      This is the Vue default slot
      <AA v-if="showFlag" :disappearTime="5" ref="AARef"/>
      <div>
        current time: {{currentTime}}
      </div>
      <BB ref="BBRef"/>
      <CC>
        <template #children="value">This is a react functional children in Vue, and received {{value}}</template>
      </CC>
    </div>
  </Basic>
</template>

<script>
import { onMounted, onUnmounted, ref, getCurrentInstance, nextTick } from 'vue'
import { applyPureReactInVue, applyReactInVue } from 'veaury'
// This is a React Component
import ReactBasic from "./react_app/Basic"
import ReactAA from "./react_app/AA"
import ReactBB from "./react_app/BB"
import ReactCC from "./react_app/CC"

export default {
  components: {
    Basic: applyReactInVue(ReactBasic),
    AA: applyReactInVue(ReactAA),
    BB: applyReactInVue(ReactBB),
    CC: applyReactInVue(ReactCC)
  },
  setup() {
    return
    let timer, timer1
    const currentTime = ref(new Date().toLocaleString())
    const foo = ref(Math.random())
    const showFlag = ref(true)
    const instance = getCurrentInstance()
    onMounted(() => {
      timer = setInterval(() => {
        currentTime.value = new Date().toLocaleString()
        foo.value = Math.random()
      }, 1000)
      timer1 = setTimeout(() => {
        showFlag.value = false
      }, 5000)
      // Get refs in next macro task
      setTimeout(() => {
        console.log(instance.refs)
      })
    })
    onUnmounted(() => {
      clearInterval(timer)
      clearInterval(timer1)
    })
    return {
      currentTime,
      foo,
      showFlag
    }
  }
}
</script>

<style scoped>
.slot {
  background: aquamarine;
  padding: 10px;
  margin: 10px;
}
</style>

// libs/veaury/dev-project-react/src/components/Basic/index.js
import { applyVueInReact } from 'veaury'
import BasicVue from './Basic'
import AAVue from './AA'
import { useEffect, useState, useRef } from 'react'

const Basic = applyVueInReact(BasicVue)
const AA = applyVueInReact(AAVue)
export default function () {
    const [state, setState] = useState({
        foo: Math.random(),
        currentTime: new Date().toLocaleString()
    })
    const [aa, setAa] = useState(true)
    const timer = useRef(null)
    const timer1 = useRef(null)
    useEffect(() => {
        timer.current = setInterval(() => {
            setState({
                foo: Math.random(),
                currentTime: new Date().toLocaleString()
            })
        }, 1000)
        timer1.current = setTimeout(() => {
            setAa(false)
        }, 5000)
        return () => {
            clearInterval(timer.current)
            clearInterval(timer1.current)
        }
    }, [])

    return <div>
        <h3>This example shows the basic usage of `applyVueInReact`.</h3>
        <h4>Using React components in Vue components.</h4>
        <Basic foo={state.foo}>
            {aa && <AA disappearTime={5}/>}
            <div className="slot">
                This is the Vue component Slot from React<br/>
                current time: {state.currentTime}
            </div>
        </Basic>
    </div>
}
