// libs/veaury/dev-project-react/src/components/useInjectPropsFromWrapper/Basic.vue
<template>
  <div class="vue-component">
    <h3>This is the Vue Component.</h3>
    the path info from 'react-router': <span style="font-weight: bold" data-testid="fullPath">{{fullPath}}</span><br/><br/>
    <button @click="changeQuery" data-testid="changeQuery">change query</button>
  </div>
</template>
<script>
import { computed } from 'vue'

export default {
  props: ['reactRouter'],
  // do not destructure props
  setup(props) {
    function changeQuery() {
      props.reactRouter?.navigate(`?a=${Math.random()}`, {replace: true})
    }
    const fullPath = computed(() => {
      const { location } = props.reactRouter || {}
      return location?.pathname + location?.search
    })
    return {
      fullPath,
      changeQuery
    }
  }
}
</script>
<style scoped>

</style>

// libs/veaury/dev-project-vue3/src/pages/crossProvider/react_app/Basic.js
import React, {useRef} from 'react'
import { useVueHooksInReact } from '../vueRouterAndVuexCrossingProvider'

export default function (props) {
  const { vuex, vueRoute, vueRouter } = useVueHooksInReact()
  function changeQuery() {
    vueRouter.replace({
      query: {
        a: Math.random()
      }
    })
  }
  function incrementCount() {
    vuex.dispatch('increment')
  }

  const style = useRef({
    background: '#91e7fc',
    width: 500,
    margin: 'auto',
    padding: 10,
    lineHeight: '30px'
  })
  return (<div style={style.current}>
    This is the React Component<br/>
    <span>
      the path info from 'vue-router': <span style={{fontWeight: 'bold'}} data-testid="fullPath">{vueRoute.fullPath}</span><br/>
      the count from 'vuex': <span style={{fontWeight: 'bold'}} data-testid="stateCount">{vuex.state.count}</span>
    </span><br/>
    <button onClick={changeQuery} data-testid="changeQuery">change query</button> <button onClick={incrementCount} data-testid="increment count">increment count</button>
  </div>)
}
